# -*- encoding: utf-8 -*-

=begin
#Azure OpenAI Service API

#Azure OpenAI APIs for completions and search

The version of the OpenAPI document: 2023-05-15

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "azure_openai_client/version"

Gem::Specification.new do |s|
  s.name        = "azure_openai_client"
  s.version     = AzureOpenaiClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Josh Etsenake"]
  s.email       = ["josh.etsenake@fullscript.com"]
  s.homepage    = "https://github.com/etsenake/azure-openai-client"
  s.summary     = "Azure OpenAI Service API Ruby Gem"
  s.description = "Azure OpenAI APIs for completions and search"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.5"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
