# frozen_string_literal: true

=begin
#Azure OpenAI Service API

#Azure OpenAI APIs for completions and search

OpenAPI spec version: 2023-05-15

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.42
=end

require 'spec_helper'
require 'json'

# Unit tests for AzureOpenaiClient::DefaultApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @instance = AzureOpenaiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@instance).to be_instance_of(AzureOpenaiClient::DefaultApi)
    end
  end

  # unit tests for chat_completions_create
  # Creates a completion for the chat message
  # @param body
  # @param api_version
  # @param deployment_id
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2002]
  describe 'chat_completions_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for completions_create
  # Creates a completion for the provided prompt, parameters and chosen model.
  # @param body
  # @param api_version
  # @param deployment_id
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'completions_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for embeddings_create
  # Get a vector representation of a given input that can be easily consumed by machine learning models and algorithms.
  # @param body
  # @param api_version
  # @param deployment_id The deployment id of the model which was deployed.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2001]
  describe 'embeddings_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
