=begin
#Azure OpenAI Service API

#Azure OpenAI APIs for completions and search

The version of the OpenAPI document: 2023-05-15

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for AzureOpenaiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = AzureOpenaiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(AzureOpenaiClient::DefaultApi)
    end
  end

  # unit tests for chat_completions_create
  # Creates a completion for the chat message
  # @param deployment_id 
  # @param api_version 
  # @param chat_completions_create_request 
  # @param [Hash] opts the optional parameters
  # @return [ChatCompletionsCreate200Response]
  describe 'chat_completions_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for completions_create
  # Creates a completion for the provided prompt, parameters and chosen model.
  # @param deployment_id 
  # @param api_version 
  # @param completions_create_request 
  # @param [Hash] opts the optional parameters
  # @return [CompletionsCreate200Response]
  describe 'completions_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for embeddings_create
  # Get a vector representation of a given input that can be easily consumed by machine learning models and algorithms.
  # @param deployment_id The deployment id of the model which was deployed.
  # @param api_version 
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [EmbeddingsCreate200Response]
  describe 'embeddings_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
