=begin
#Azure OpenAI Service API

#Azure OpenAI APIs for completions and search

The version of the OpenAPI document: 2023-05-15

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureOpenaiClient::ChatCompletionsCreateRequestMessagesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureOpenaiClient::ChatCompletionsCreateRequestMessagesInner do
  let(:instance) { AzureOpenaiClient::ChatCompletionsCreateRequestMessagesInner.new }

  describe 'test an instance of ChatCompletionsCreateRequestMessagesInner' do
    it 'should create an instance of ChatCompletionsCreateRequestMessagesInner' do
      expect(instance).to be_instance_of(AzureOpenaiClient::ChatCompletionsCreateRequestMessagesInner)
    end
  end
  describe 'test attribute "role"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["system", "user", "assistant"])
      # validator.allowable_values.each do |value|
      #   expect { instance.role = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "content"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
