=begin
#Azure OpenAI Service API

#Azure OpenAI APIs for completions and search

The version of the OpenAPI document: 2023-05-15

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureOpenaiClient::ChatCompletionsCreate200ResponseChoicesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureOpenaiClient::ChatCompletionsCreate200ResponseChoicesInner do
  let(:instance) { AzureOpenaiClient::ChatCompletionsCreate200ResponseChoicesInner.new }

  describe 'test an instance of ChatCompletionsCreate200ResponseChoicesInner' do
    it 'should create an instance of ChatCompletionsCreate200ResponseChoicesInner' do
      expect(instance).to be_instance_of(AzureOpenaiClient::ChatCompletionsCreate200ResponseChoicesInner)
    end
  end
  describe 'test attribute "index"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "finish_reason"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
