=begin
#Azure OpenAI Service API

#Azure OpenAI APIs for completions and search

The version of the OpenAPI document: 2023-05-15

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureOpenaiClient::CompletionsCreate200ResponseChoicesInnerLogprobs
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureOpenaiClient::CompletionsCreate200ResponseChoicesInnerLogprobs do
  let(:instance) { AzureOpenaiClient::CompletionsCreate200ResponseChoicesInnerLogprobs.new }

  describe 'test an instance of CompletionsCreate200ResponseChoicesInnerLogprobs' do
    it 'should create an instance of CompletionsCreate200ResponseChoicesInnerLogprobs' do
      expect(instance).to be_instance_of(AzureOpenaiClient::CompletionsCreate200ResponseChoicesInnerLogprobs)
    end
  end
  describe 'test attribute "tokens"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "token_logprobs"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "top_logprobs"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "text_offset"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
