=begin
#Azure OpenAI Service API

#Azure OpenAI APIs for completions and search

The version of the OpenAPI document: 2023-05-15

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureOpenaiClient::CompletionsCreate200ResponseUsage
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureOpenaiClient::CompletionsCreate200ResponseUsage do
  let(:instance) { AzureOpenaiClient::CompletionsCreate200ResponseUsage.new }

  describe 'test an instance of CompletionsCreate200ResponseUsage' do
    it 'should create an instance of CompletionsCreate200ResponseUsage' do
      expect(instance).to be_instance_of(AzureOpenaiClient::CompletionsCreate200ResponseUsage)
    end
  end
  describe 'test attribute "completion_tokens"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "prompt_tokens"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "total_tokens"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
