=begin
#Azure OpenAI Service API

#Azure OpenAI APIs for completions and search

The version of the OpenAPI document: 2023-05-15

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AzureOpenaiClient::EmbeddingsCreate200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AzureOpenaiClient::EmbeddingsCreate200Response do
  let(:instance) { AzureOpenaiClient::EmbeddingsCreate200Response.new }

  describe 'test an instance of EmbeddingsCreate200Response' do
    it 'should create an instance of EmbeddingsCreate200Response' do
      expect(instance).to be_instance_of(AzureOpenaiClient::EmbeddingsCreate200Response)
    end
  end
  describe 'test attribute "object"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "model"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "usage"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
